### ISSUE TITLE
deleting a polygon from table causes an error

### ISSUE THREAD

**Issue by dhasterok** [dhasterok/LaserMapExplorer#37]
Traceback (most recent call last):
  File "/Users/derrickhasterok/GitHub/LaserMapExplorer/main.py", line 724, in <lambda>
    self.toolButtonPolyDelete.clicked.connect(lambda: self.table_fcn.delete_row(self.tableWidgetPolyPoints))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/derrickhasterok/GitHub/LaserMapExplorer/main.py", line 12118, in delete_row
    for p in self.main_window.polygon.polygons[p_id]:
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 1

**Comment by shavinkalu23** [comment]
Polygons are segregated by sample id, which has not been updated in Table_fcn, the polygons  should be accessed by self.main_window.polygon.polygons[self.main_window.sample_id]
