### ISSUE TITLE
Autoscale spinboxes not updating, seem to have no effect

### ISSUE THREAD

**Issue by dhasterok** [dhasterok/LaserMapExplorer#44]
Autoscale spin boxes seem to have no effect upon change and are all initially set to 0.

**Comment by dhasterok** [comment]
The spinBoxes have been converted to lineEdit fields with QDoubleValidators to restrict them.  While spinBoxes are nice in a way, lineEdits seem easier to deal with.  Ran into issue that they are still initially set.  Need to use update_spinboxes which is no longer called from change_sample.  Requires 'parameters', but which ones?

**Comment by shavinkalu23** [comment]
update_spinboxes was edited, to obtain the auto scale parameters and neg value handling value from 'Analyte Info' or 'Ratio Info' and the UI is updated based on these values
